### ISSUE TITLE
Login triggers somewhat off?

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/Blockheads-MessageBot#22] opened 2016-06-08 20:18 UTC
Ignore the mold comment.  LOL  The bot was not running at the start when I did /players.  Then I started it and got the message about players Kekeiekek, and 790002311467 who weren't even online.  And nothing for AHXHSYDNYSNEYSNT or Cinday  who WERE online.  Is that normal?

SERVER: There are 2 players connected:
AHXHSYDNYSNEYSNT | 173.214.217.203 | 16b0a35a8f78524714683eb7a985c42f
CINDAYTRAIN1 | 68.97.173.124 | 8619ecb5d243a5c002d7cb66c03cb5ba
SERVER: NEWS: Sky Bucks can now buy you rank kits and ownership signs!! You get Sky Bucks by joining the server and doing quests. Type /quest for current quest details. Type /ranks for rank kit details, or /bucks for commands
SERVER: Welcome to Skylands Arena Kekeiekek. Be sure to read the rules on the welcome page. This isn't your average server.
SERVER: Welcome to Skylands Arena 790002311467. Be sure to read the rules on the welcome page. This isn't your average server.
SERVER: Welcome to Skylands Arena Cindaytrain1. Be sure to read the rules on the welcome page. This isn't your average server.
SERVER: Added daily reward of Sky Bucks to Kekeiekek.
SERVER: Added daily reward of Sky Bucks to 790002311467.
AHXHSYDNYSNEYSNT: can you make me mold
SERVER: /players
CINDAYTRAIN1: Mold?
SERVER: There are 2 players connected:
AHXHSYDNYSNEYSNT | 173.214.217.203 | 16b0a35a8f78524714683eb7a985c42f
CINDAYTRAIN1 | 68.97.173.124 | 8619ecb5d243a5c002d7cb66c03cb5ba

**Comment by Bibliofile** [comment] 2016-06-09 04:35
Well that's rather strange, not sure yet what happened there... Looking into it.

**Comment by Bibliofile** [comment] 2016-08-14 03:44
Finally found the cause of this! Wow, very surprised it escaped undetected for so long. Fix will be out tomorrow evening at the latest.

**Comment by Bibliofile** [comment] 2016-09-07 02:12
I believe I've figured out what happened here, still not entirely sure *why* it happened though... 

You said the portal was open before the bot was loaded, did Kekeiekek and 790002311467 join the server earlier (still in the portal log)?

**Comment by jemnidad** [comment] 2016-09-07 02:58
Yes, I believe they logged in while the portal chat was up, but before I
loaded the bot.

I often do a reload of my browser when my laptop wakes up from standby and
then start up the bot.  Sometimes the reload wasn't really necessary. I
just was making sure it was getting a refreshed state.

**Comment by Gerrit0** [comment] 2016-09-07 03:03
That's what happened then, the bot gets some history of chat when first starting up (if available) to show to the owner. 

As the currency extension loaded before the get chat request loaded, it caught those join messages and thought those players were joining. 

I will implement a delay before loading extensions to counteract this sooner or later.

**Comment by Bibliofile** [comment] 2016-09-07 03:08
That's what happened then, the bot gets some history of chat when first starting up (if available) to show to the owner.

As the currency extension loaded before the get chat request loaded, it caught those join messages and thought those players were joining.

I will implement a delay before loading extensions to counteract this sooner or later.

**Comment by jemnidad** [comment] 2016-09-07 17:22
Hey Gerrit, if that's your real name.  Depending on how you reply, I think,
it shows your name.


Jeremy

**Comment by Bibliofile** [comment] 2016-10-16 18:53
This is now resolved with 6.0 :)

(Yep, that's me... 2 github accounts...)

**Closed by Bibliofile** 2016-10-16 18:53 UTC
