### ISSUE TITLE
PvP messages death not working.

### ISSUE THREAD

**Issue by Wingysam** [Bibliofile/Blockheads-MessageBot#20] opened 2016-05-24 23:37 UTC
I noticed that the death trigger does not work. I do not think there is a log entry when a player dies.

**Comment by dapersonmgn** [comment] 2016-05-25 03:47
Is the world a 1 hit death world? Deaths don't log in those worlds.

**Comment by Bibliofile** [comment] 2016-05-25 13:35
I believe they don't log in custom worlds at all - I tried killing myself in a custom world with normal health / death settings and nothing...

**Comment by dapersonmgn** [comment] 2016-05-25 13:46
Dang it! I'll add a warning to the extension about that.

**Comment by Bibliofile** [comment] 2016-05-25 16:29
Marking this as resolved as the problem isn't with the bot itself, and it seems it has been "fixed".

**Closed by Bibliofile** 2016-05-25 16:29 UTC
